# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Postmark Capital
email: andrew@postmarkcapital.com
description: > # this means to ignore newlines until "baseurl:"
  Postmark Capital is awesome for reasons
baseurl: "/dev" # the subpath of your site, e.g. /blog
url: "http://jdauriemma.startlogic.com" # the base hostname & protocol for your site
twitter_username: postmarkcapital

# Build settings
markdown: kramdown
